### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by comradekingu** [deep-gaurav/rusty_pipe#4]
GPLv3+?

**Comment by deep-gaurav** [comment]
Yeah, currently no license, I need to add license and readme to rustypipe and sister projects.

License will be same as NewPipeExtractor as it's based on it, so yeah, GPL v3+

**Comment by deep-gaurav** [comment]
Resolved by #5

**Comment by EmanuelLoos** [comment]
If you want to license your changes under the same terms as NewPipeExtractor, the [GPLv3+ also called GPLv3-or-later](http://www.gnu.org/licenses/gpl-faq.html#VersionThreeOrLater) which allows usage of the code under the terms of the GPLv3 or any later version of the license, you would need a copyright and license notice stating that as NewPipeExtractor has [here](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/copyright) and [at the beginning of each file of the code](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/stream/AudioStream.java) (some IDEs have a feature to do that automatically when you create a new file). Note that you are not obligated to grant usage under the terms of any newer version of the GPL because you are only obligated to follow one version of the GPL grander or the same as version 3. However, I would very much recommend you to, because if it is not done it can make usage under a newer version of the GPL when it comes out very difficult as every contributor would have to be asked again if he/she agrees to it which is almost impossible for larger projects.
